### ISSUE TITLE
Issue handling non major.minor versioning for dependency IPTables-Parse

### ISSUE THREAD

**Issue by cydactyl** [mrash/IPTables-ChainMgr#4]
OS:Arch
Versions:
IPTables-ChainMgr 1.5
IPTables-Parse 1.6.1

While updating the AUR packages I noticed the programs inability to handle the major.minor.revision build format of IPTables-Parse.

`Argument "1.6.1" isn't numeric in numeric gt (>) at
/usr/share/perl5/vendor_perl/IPTables/ChainMgr.pm line 259.`

**Comment by mrash** [comment]
Thanks, I'll get this fixed over the next couple of days.

**Comment by cydactyl** [comment]
Any update on this issue?

**Comment by mrash** [comment]
Sorry it took so long to fix that one.
